
--MEMBER 테이블
CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(40) NOT NULL,
    USER_NAME VARCHAR2(15) NOT NULL,
    BIRTHDATE VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20),
    USER_EMAIL VARCHAR2(40),
    USER_ROLE NUMBER DEFAULT 1,
    ADDRESS VARCHAR2(40),
    USER_IMG VARCHAR(40), 
    TRAVEL VARCHAR2(40) NOT NULL,    
    CREATE_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.BIRTHDATE IS '생년월일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '회원타입(1 유저, 2 어드민)';
COMMENT ON COLUMN MEMBER.ADDRESS IS '거주지';
COMMENT ON COLUMN MEMBER.USER_IMG IS '프로필사진';
COMMENT ON COLUMN MEMBER.TRAVEL IS '가고싶은지역';
COMMENT ON COLUMN MEMBER.CREATE_DATE IS '회원생성일자';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '회원수정일자';
COMMENT ON COLUMN MEMBER.STATUS IS '회원상태값(Y/N)';

CREATE SEQUENCE SEQ_UNO;


--BOARD 테이블
CREATE TABLE BOARD (	
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_WRITER_NO NUMBER, 
    LOC_NAME VARCHAR2(10),
    BOARD_NAME VARCHAR2(10),
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(2000),
    BOARD_READCOUNT NUMBER DEFAULT 0, 
    BOARD_ORIGINAL_FILENAME VARCHAR2(100), 
	BOARD_RENAMED_FILENAME VARCHAR2(100),
    TRANSPORT VARCHAR2(20),
    TRAVEL_MONEY VARCHAR2(20),
    BOARD_SCORE NUMBER,
    BOARD_CREATE_DATE DATE DEFAULT SYSDATE, 
    BOARD_MODIFY_DATE DATE DEFAULT SYSDATE, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
	CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(BOARD_WRITER_NO) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_WRITER_NO IS '회원번호';
COMMENT ON COLUMN BOARD.LOC_NAME IS '지역이름';
COMMENT ON COLUMN BOARD.BOARD_NAME IS '게시판이름';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_READCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_ORIGINAL_FILENAME IS '파일이름';
COMMENT ON COLUMN BOARD.BOARD_RENAMED_FILENAME IS '변경된파일이름';
COMMENT ON COLUMN BOARD.TRANSPORT IS '교통수단';
COMMENT ON COLUMN BOARD.TRAVEL_MONEY IS '경비';
COMMENT ON COLUMN BOARD.BOARD_SCORE IS '별점';
COMMENT ON COLUMN BOARD.BOARD_CREATE_DATE IS '등록일자';
COMMENT ON COLUMN BOARD.BOARD_MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN BOARD.STATUS IS '게시글상태 (Y/N)';

CREATE SEQUENCE SEQ_BOARD_NO;

--댓글테이블
CREATE TABLE COMMENTS (
    COMMENT_NO NUMBER PRIMARY KEY,
    COMMENT_BOARD_NO NUMBER,
    COMMENT_WRITER_NO NUMBER,
    COMMENT_CONTENT VARCHAR2(200),
    COMMENT_CREATE_DATE DATE DEFAULT SYSDATE,
    COMMENT_MODIFY_DATE DATE DEFAULT SYSDATE, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    CONSTRAINT FK_COMMENT_WRITER FOREIGN KEY(COMMENT_WRITER_NO) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL,
    CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY(COMMENT_BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE
);
COMMENT ON COLUMN COMMENTS.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN COMMENTS.COMMENT_BOARD_NO IS '게시글번호';
COMMENT ON COLUMN COMMENTS.COMMENT_WRITER_NO IS '회원번호';
COMMENT ON COLUMN COMMENTS.COMMENT_CONTENT IS '댓글내용';
COMMENT ON COLUMN COMMENTS.COMMENT_CREATE_DATE IS '등록일자';
COMMENT ON COLUMN COMMENTS.COMMENT_MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN COMMENTS.STATUS IS '댓글상태(Y/N)';


CREATE SEQUENCE SEQ_COMMENT_NO;

--방문자수
CREATE TABLE VISIT(
    V_DATE DATE DEFAULT SYSDATE
)
